package app

const (
	ONBOARDING_TASK_QUEUE   = "ONBOARDING_TASK_QUEUE"
	ACCEPTANCE_TIME         = 120 // Time in seconds to wait for claim codes to be accepted
	SCENARIO_HAPPY_PATH     = "SCENARIO_HAPPY_PATH"
	SCENARIO_BUG            = "SCENARIO_BUG"
	SCENARIO_FLAKEY_API     = "SCENARIO_FLAKEY_API"
	SCENARIO_UNEXPECTED_BUG = "SCENARIO_UNEXPECTED_BUG"
	SCENARIO_EXPECTED_ERROR = "SCENARIO_EXPECTED_ERROR"
)
